version: '3.3'

services:
  app:
    container_name: cat
    build:
      context: .
      dockerfile: Dockerfile
    command: python3 -m userbot
    restart: on-failure
    ports:
        - "6969:6969"